/* Seed sample books into librarydb.books */

const books = [
  {
    _id: "b_horror_001",
    title: "The Whispering Corridor",
    author: "A. K. Rao",
    genre: "horror",
    description: "A quiet hostel hallway that remembers every secret ever spoken. When freshmen students move into the historic East Wing of a century-old university hostel, they dismiss the stories of a whispering phantom as mere hazing rituals. But when the soft rustling in the corridor begins reciting their private, hidden memories at midnight, a small group of friends is forced to investigate. They discover that the wing hides a tragic history, and the hallway is demanding a confession before the final door locks.",
    marketPrice: 299,
    coverImageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_romance_001",
    title: "Letters in Monochrome",
    author: "Meera Iyer",
    genre: "romance",
    description: "Two strangers fall in love through unsent letters left in a café. Maya, a reserved graphic designer, and Kabir, a traveling photojournalist, have never spoken, yet they share a corner booth at Café Mocha on different days of the week. When Kabir accidentally leaves behind a notebook containing a heartfelt letter, Maya writes a response. Soon, a secret correspondence blossoms, but as their letters grow deeper, they must decide if their connection can survive the harsh light of reality.",
    marketPrice: 249,
    coverImageUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_comedy_001",
    title: "The Accidental Stand‑Up",
    author: "N. S. Verma",
    genre: "comedy",
    description: "A shy librarian is mistaken for a comedian and rolls with it. Harish Verma prefers quiet book stacks to public speaking. But when a bookkeeping error lists him as the headlining act at a local comedy club, Harish is pushed onto the stage. Too terrified to explain the mistake, he delivers a dry, awkward rant about cataloguing systems that brings the house down. Now, Harish must lead a double life, juggling his quiet day job with a booming, unexpected comedy career.",
    marketPrice: 199,
    coverImageUrl: "https://images.unsplash.com/photo-1455885666463-42d1f67ce36a?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_scifi_001",
    title: "Orbit of Ink",
    author: "J. Sen",
    genre: "sci-fi",
    description: "A station archivist finds a book that rewrites reality, page by page. Deep inside the orbital archive station near Saturn, Noah spends his days digitizing ancient paper books. When he discovers a blank, leather-bound diary that is not listed in any index, he writes his name in it. To his shock, the station's computer records instantly change to match his entry. Noah soon realizes that writing in the book alters physical reality—but every change carries a heavy price for the crew.",
    marketPrice: 399,
    coverImageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_thriller_001",
    title: "Index of Lies",
    author: "R. K. Malhotra",
    genre: "thriller",
    description: "A missing catalogue card leads to a chain of impossible crimes. When chief archivist Dev finds that a vital index card from 1974 has been cut from the master catalog, he suspects a simple case of vandalism. But within hours, the researcher who requested the card is found dead in the archive room. Dev is pulled into a high-stakes conspiracy involving forged corporate registers and historical cover-ups. He must solve the riddle of the index card before he becomes the next target.",
    marketPrice: 349,
    coverImageUrl: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_fantasy_001",
    title: "The Paper Crown",
    author: "S. Das",
    genre: "fantasy",
    description: "A kingdom where every decree is bound into spellbooks guarded by owls. In the magical realm of Eldoria, royal decrees are written on sacred parchment that binds the citizens' actions by law. When a young scribe accidentally drafts a decree that grants independence to the kingdom's enchanted creatures, she triggers a magical uprising. With the aid of a rebellious owl warden, she must retrieve the decree from the royal vault before the wizard council executes a cleansing spell.",
    marketPrice: 459,
    coverImageUrl: "https://images.unsplash.com/photo-1528459105426-b9548367069b?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_nonfiction_001",
    title: "Small Habits, Big Focus",
    author: "K. Anand",
    genre: "non-fiction",
    description: "A practical guide to building reading routines and sustained concentration. In this bestselling self-help guide, cognitive psychologist Dr. Anand explores how modern screens have rewired our attention spans and how we can reclaim our focus. Using actionable exercises, reading schedules, and environmental design, this book teaches you how to read more deeply, work with higher efficiency, and protect your mind from constant digital noise.",
    marketPrice: 279,
    coverImageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_mystery_001",
    title: "The Silent Bookmark",
    author: "Tara Menon",
    genre: "mystery",
    description: "Every time a bookmark appears, someone disappears. A librarian investigates. At the Grand Municipal Library, a string of mysterious disappearances has left the police baffled. The only clue is a vintage leather bookmark left behind in the book the victim last checked out. Head archivist Tara Menon decides to investigate the pattern herself. She is drawn into an underground network of secret passages and a century-old mystery that leads to the library's founding fathers.",
    marketPrice: 329,
    coverImageUrl: "https://images.unsplash.com/photo-1474932430478-367d0ae0e0e9?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_mystery_002",
    title: "Shadows of the Manor",
    author: "Clara Vance",
    genre: "mystery",
    description: "When an eccentric billionaire summons five estranged cousins to his remote cliffside estate for the reading of his will, they expect a simple inheritance. Instead, they are met with a locked diary, a series of cryptic riddles, and the unsettling realization that their host has been dead for weeks. As a fierce winter storm cuts off all contact with the outside world, family secrets begin to unravel, and they must decipher the clues before the killer among them strikes again.",
    marketPrice: 389,
    coverImageUrl: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_fantasy_002",
    title: "The Weaver of Whispers",
    author: "Kellen Stone",
    genre: "fantasy",
    description: "In the magical city of Oakhaven, memories are a currency that can be bought, sold, and traded. Lyra, a humble apprentice weaver, possesses the rare gift of spinning raw emotions into silken threads of memory. But when she accidentally weaves a thread containing a dark secret about the city's ruling council, she becomes the target of ruthless spell-hunters. Now, Lyra must navigate a treacherous web of politics and ancient spells to protect the city's forgotten history.",
    marketPrice: 429,
    coverImageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_scifi_002",
    title: "Chronicles of Echo",
    author: "Dr. Evelyn Ray",
    genre: "sci-fi",
    description: "Dr. Alistair Finch has spent his life studying the Echo—a mysterious cosmic anomaly that reflects fragments of historical events back into space. When a sudden shift in the Echo begins projecting a future catastrophe that leads to the complete erasure of humanity, Alistair is forced to partner with a rogue pilot and a banned artificial intelligence. Together, they embark on a dangerous voyage to the heart of the anomaly to alter the timeline before history resets.",
    marketPrice: 489,
    coverImageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_thriller_002",
    title: "The Final Equation",
    author: "Arthur Pendelton",
    genre: "thriller",
    description: "After a brilliant mathematician is found dead in his study, detective Marcus Vance discovers a hidden chalkboard covered in complex equations. The last formula, left unfinished, holds the key to a predictive algorithm capable of cracking global encryption keys. As international intelligence agencies and cyber-terrorists descend on London to claim the equation, Marcus must race against the clock to solve the final variables and prevent a global security collapse.",
    marketPrice: 359,
    coverImageUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_nonfiction_002",
    title: "The Mindful Path",
    author: "Dr. Sarah Jenkins",
    genre: "non-fiction",
    description: "In an age of constant distraction and digital noise, finding mental clarity can feel like an impossible task. Dr. Sarah Jenkins offers a groundbreaking, science-backed framework for reclaiming your attention and cultivating deep focus. Through a combination of cognitive behavioral techniques, behavioral psychology, and practical daily exercises, this guide provides the tools you need to build long-term habits, reduce stress, and achieve peak performance in your professional and personal life.",
    marketPrice: 299,
    coverImageUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_romance_002",
    title: "Sunset at the Bookstore",
    author: "Laura Jenkins",
    genre: "romance",
    description: "Elena, a struggling artist, takes a part-time job at 'The Pages of Time', a cozy independent bookstore in the heart of San Francisco. There, she meets Julian, a reserved architecture student who spends his evenings sketching in the corner of the shop. As they bond over vintage paperbacks and shared dreams, a secret from Julian's past threatens to tear them apart. A heartwarming tale of second chances, art, and the power of love to heal old wounds.",
    marketPrice: 269,
    coverImageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_horror_002",
    title: "Echoes from the Deep",
    author: "Thomas Vance",
    genre: "horror",
    description: "When a deep-sea research submarine loses communication during a dive into the Mariana Trench, a salvage crew is sent to recover the vessel. What they find is a derelict sub, free of physical damage but completely deserted. As they explore the cold, dark corridors, they realize they are not alone. Something ancient and predatory has awakened in the depths, hunting them through sound and feeding on their deepest fears.",
    marketPrice: 319,
    coverImageUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_mystery_003",
    title: "The Curio Shop Conspiracy",
    author: "R. J. Thorne",
    genre: "mystery",
    description: "When antique dealer Silas Thorne acquires a rare 19th-century music box, he unlocks more than just a mechanical tune. Hidden inside the double-bottom casing is a coded map dating back to the height of the industrial revolution. As Silas is plunged into a hidden conflict between rival secret societies, he must rely on his knowledge of antiquities and code-breaking to find the relic before it falls into dangerous hands.",
    marketPrice: 369,
    coverImageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_fantasy_003",
    title: "Gilded Wings",
    author: "Seraphina Vance",
    genre: "fantasy",
    description: "High above the clouds, the sky-island kingdom of Aethelgard is ruled by the iron-fisted Sky Lords and their mechanical griffins. Aria, a young sky-courier, dreams of joining the legendary Griffin Academy. When she rescues a fallen sky-lord carrying a mysterious golden feather, she is thrust into a rebellion that could shatter the fragile peace of the skies. She must decide where her loyalties lie before the heavens ignite in war.",
    marketPrice: 479,
    coverImageUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_scifi_003",
    title: "Singularity's Shadow",
    author: "Raymond Croft",
    genre: "sci-fi",
    description: "In the year 2184, human consciousness can be uploaded to a vast cybernetic collective known as the Grid. When a digital virus known as the Shadow begins corrupting minds and erasing uploaded identities, a cynical cyber-detective and an android archivist are hired to investigate the source. Their journey takes them from the neon-lit virtual cities to the ruins of old Earth, where they uncover a conspiracy that challenges the definition of life itself.",
    marketPrice: 449,
    coverImageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_history_001",
    title: "The Silk Road Lost Chronicles",
    author: "Dr. Arjun Mehta",
    genre: "history",
    description: "For centuries, the Silk Road was a channel for trade, culture, and ideas across Europe and Asia. Dr. Arjun Mehta brings to light forgotten manuscripts and archaeological discoveries from ancient desert outposts. From the daily lives of camel caravaneers to the espionage of medieval empires, this narrative history offers a vivid, gripping account of the merchants, explorers, and scholars who shaped the ancient global economy.",
    marketPrice: 399,
    coverImageUrl: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=600&q=80",
  },
  {
    _id: "b_biography_001",
    title: "Uncharted Waters: The Life of Captain Thomas",
    author: "Helena Ross",
    genre: "biography",
    description: "The definitive biography of Captain Arthur Thomas, the pioneering 18th-century navigator who mapped the uncharted coastlines of the Pacific. Drawing on newly discovered journals, personal letters, and ship logs, Helena Ross paints a complex portrait of a brilliant but driven explorer. It explores his encounters with indigenous cultures, his battles with mutinous crews, and the personal sacrifices that paved the way for modern cartography.",
    marketPrice: 329,
    coverImageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80",
  }
];

const result = db.books.bulkWrite(
  books.map((b) => ({
    updateOne: {
      filter: { _id: b._id },
      update: { $set: b },
      upsert: true,
    },
  }))
);

print("Seeded/updated books:", JSON.stringify(result, null, 2));
